-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkSFRPqNEdmdjiTv8
w/8pDBvGNgPBGyuzze6vfWLM/DCgCgYIKoZIzj0DAQehRANCAATdOLi83IiKuvjT
4ghLQ+SLBhyeJ17VIoPWlDEKy9aPYPhzCmaKO4q3OuazyZzgEWaaOancTiQdYwGR
q/qLV93k
-----END PRIVATE KEY-----