name: alaman
description: "A new Flutter project."

publish_to: "none"

version: 3.2.1+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  easy_localization: ^3.0.4

  flutter_hooks: ^0.20.5
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  form_field_validator: ^1.1.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  responsive_framework: ^1.1.1
  riverpod_annotation: ^2.3.4
  transparent_image: ^2.0.1
  flutter_widget_from_html: ^0.14.11
  shimmer: ^3.0.0
  widgetbook: ^3.7.1
  url_launcher: ^6.2.5
  cached_network_image: ^3.3.1
  geolocator: ^11.0.0
  tuple: ^2.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  widgetbook_annotation: ^3.1.0
  jovial_svg: ^1.1.20
  lottie: ^3.1.0
  sign_in_with_apple: ^6.0.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.28.0
  video_player: ^2.8.4
  firebase_messaging: ^14.8.0
  device_info_plus: ^10.0.1
  flutter_native_splash: ^2.4.0
  google_maps_flutter: ^2.2.8
 
dev_dependencies:
  auto_route_generator:
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/
    - shorebird.yaml

  fonts:
    - family: Satchi
      fonts:
        - asset: assets/Satoshi.ttf
