// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBupD7l-EZ4QJYYfrGa6k-13UGYqsEewns',
    appId: '1:44588225737:android:b8b33ca689bdaad5a56918',
    messagingSenderId: '44588225737',
    projectId: 'al-aman-283317',
    storageBucket: 'al-aman-283317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPhXCh3YIkNhtFKICEbSz1d6XCT64prAs',
    appId: '1:44588225737:ios:a63edacb1bd81499a56918',
    messagingSenderId: '44588225737',
    projectId: 'al-aman-283317',
    storageBucket: 'al-aman-283317.appspot.com',
    androidClientId: '44588225737-q5pdl4dip2ib63o469h929umdj996c34.apps.googleusercontent.com',
    iosClientId: '44588225737-ds9m4quan6v0v9di19mpufb3l4k912cp.apps.googleusercontent.com',
    iosBundleId: 'com.alamanfund.alaman',
  );
}
